services:
    web:
        container_name: "fragment-cache-addon"
        build:
            context: .docker
            dockerfile: 8.4/apache/Dockerfile
            args:
                WWWUSER: '${WWWUSER:-1000}'
                WWWGROUP: '${WWWGROUP:-1000}'
                NODE_VERSION: '20'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8083}:80'
            - '${VITE_PORT:-5187}:${VITE_PORT:-5187}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            WWWGROUP: '${WWWGROUP:-1000}'
            PHP_IDE_CONFIG: "serverName=docker" # Must match the server name in PHPStorm's server configuration
            XDEBUG_MODE: '${DEEM_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${DEEM_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            SUPERVISOR_PHP_USER: 'www-data'
        volumes:
            - '.:/var/www/html' # this adds/attach the current codebase to the container, basically it mirrors the codebase in container
            - './.docker/common/php/20-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
            - './.docker/common/php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini'
            - './logs/:/var/log'
        networks:
            - optimesh

networks:
    optimesh:
        driver: bridge
        name: optimesh


